# This is the mods.toml file for Material Ascension
modLoader="javafml"
loaderVersion="[47,)" # Forge 47.x is for Minecraft 1.20.1
license="MIT"         # Change this if you use a different license

[[mods]]
modId="materialascension"
version="1.0.0"                 # Put your mod version here
displayName="Material Ascension"
logoFile="icon.png"             # Optional logo in your resources root
authors="voxelparrot"        # Optional
description='''Integrates Create, Basic Weapons, and More Ores More Gems together and adds several legendary weapons to create in the late game'''

# Dependencies

[[dependencies.materialascension]]
modId="forge"
mandatory=true
versionRange="[47,)"        # Require Forge 47.x (MC 1.20.1)
ordering="NONE"
side="BOTH"

[[dependencies.materialascension]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"  # Works on Minecraft 1.20.x
ordering="NONE"
side="BOTH"

[[dependencies.materialascension]]
modId="more_ores_more_gems"
mandatory=false
ordering="AFTER"
side="BOTH"

[[dependencies.materialascension]]
modId="create"
mandatory=false
ordering="AFTER"
side="BOTH"

[[dependencies.materialascension]]
modId="basicweapons"
mandatory=false
ordering="AFTER"
side="BOTH"
